### ISSUE TITLE
Scheduled Action

### ISSUE THREAD

**Issue by sbuhl** [sbuhl/gse_custo#11]
Check everyday, 
SO in state "no delivered" or "partially delivered"

Marqueur pour identifier les SO qui sont en retard de livraison, 
dont leur livraison est expliquée/explicable, etc.

**Comment by shortcut1337** [comment]
Je ne sais pas si ça m'est destiné (je crois que tu m'assignes quand c'est le cas)?

Mais si oui: peux-tu reformuler et/ou donner plus de détails ?
