### ISSUE TITLE
Prevent duplicate invoice

### ISSUE THREAD

**Issue by sbuhl** [sbuhl/gse_custo#7]
Is it possible to remove the button "duplicate" on the invoices?

**Comment by shortcut1337** [comment]
Visually yes easily, but:
1. For everyone?
2. Don't you want something at the python level that prevents users (some of them?) to do it, on top of removing the button ?
Eg, if they find another way to access the copy behavior like from another form view or using RPC (probably doesn't apply as its your internal user) or if you introduce a new form view later or anything ?

**Comment by shortcut1337** [comment]
https://github.com/sbuhl/gse_custo/pull/9

**Comment by shortcut1337** [comment]
Note que les factures fournisseurs et clients utilisent la meme form view, vu que même model, donc là ça s'applique aux 2, faut-il l'empecher sur une seule ?

**Comment by sbuhl** [comment]
Sorry, j'avais pas vu tes commentaires bizarrement. 
1. Si moyen de le laisser accessible pour les account_manager, comme tu as +- fais, ça serait mieux. 
2. Ou alors laisser certains le faire en python, étant donné que ça doit rester exceptionnel.

**Comment by shortcut1337** [comment]
Continuons la discussion sur la PR liée :)
J'ai répondu là bas: https://github.com/sbuhl/gse_custo/pull/9#discussion_r1118136893
