### ISSUE TITLE
Add Payment status on SO

### ISSUE THREAD

**Issue by sbuhl** [sbuhl/gse_custo#8]
in the sale.order list view
add a column (hidden by default) "Payment Status"
Linked to the invoice(s).
If one invoice or more is not paid => Not Paid
If one or more is in payment => In Payment
If all invoices are paid (not in payment) => Paid

**Comment by sbuhl** [comment]
@shortcut1337  
Besoin de plus d'explications ici?

**Comment by shortcut1337** [comment]
On peut fermer je crois, vu qu'il y a une PR maintenant (je viens d'y push un commit)
